openapi: 3.0.0
info:
  title: Eurika School API
  version: 1.0.0
  description: API для школьного портала Eurika

servers:
  - url: https://api.eurika.school/v1

paths:
  /auth/login:
    post:
      summary: Авторизация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /users/me:
    get:
      summary: Получить профиль текущего пользователя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Профиль пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /schedule/today:
    get:
      summary: Получить расписание на сегодня
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список занятий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClassSession'

  /schedule/week:
    get:
      summary: Получить расписание на неделю
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: day
          schema:
            type: string
            enum: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
          description: Фильтр по дню недели (опционально)
      responses:
        '200':
          description: Список занятий за неделю
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClassSession'

  /grades:
    get:
      summary: Получить оценки пользователя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список оценок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Grade'

  /video-lessons:
    get:
      summary: Получить видеоуроки
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список видеоуроков
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoLesson'

  /homework:
    get:
      summary: Получить список домашних заданий
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [done, not_done]
          description: Фильтр по статусу выполнения
        - in: query
          name: subject
          schema:
            type: string
          description: Фильтр по предмету
        - in: query
          name: teacher
          schema:
            type: string
          description: Фильтр по учителю
      responses:
        '200':
          description: Список домашних заданий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Homework'

  /homework/{id}:
    get:
      summary: Получить одно домашнее задание по ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Детали задания
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Homework'

  /homework/{id}/status:
    put:
      summary: Изменить статус выполнения домашнего задания
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [done, not_done]
      responses:
        '200':
          description: Статус успешно обновлён

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        full_name:
          type: string
        email:
          type: string

    ClassSession:
      type: object
      properties:
        id:
          type: integer
        subject:
          type: string
        classroom:
          type: string
        day_of_week:
          type: string
          enum: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time

    Grade:
      type: object
      properties:
        subject:
          type: string
        mark:
          type: string

    Homework:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        subject:
          type: string
        teacher:
          type: string
        published_at:
          type: string
          format: date
        due_date:
          type: string
          format: date
        status:
          type: string
          enum: [done, not_done]

    VideoLesson:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        url:
          type: string
