openapi: 3.0.0
info:
  title: API преподавателя
  version: 1.0.0
  description: API для работы с функциями преподавателя в образовательной платформе

servers:
  - url: https://api.education.com/v1
    description: Основной сервер

tags:
  - name: Расписание
    description: Управление расписанием занятий
  - name: Занятия
    description: Управление занятиями и их материалами
  - name: Курсы
    description: Управление курсами преподавателя
  - name: Студенты и группы
    description: Работа со студентами и группами
  - name: Домашние задания
    description: Создание и управление домашними заданиями
  - name: Видеоуроки
    description: Управление видеоматериалами
  - name: Сообщения
    description: Система обмена сообщениями
  - name: Профиль
    description: Управление профилем преподавателя
  - name: Публичные данные
    description: Открытые данные о преподавателях и курсах

paths:
  # ===== РАСПИСАНИЕ =====
  /teacher/schedule/today:
    get:
      tags: [Расписание]
      summary: Получить расписание на сегодня
      description: Возвращает все занятия преподавателя на текущий день
      responses:
        '200':
          description: Расписание успешно получено
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  # ===== ЗАНЯТИЯ =====
  /teacher/lessons:
    get:
      tags: [Занятия]
      summary: Получить список всех занятий
      description: Возвращает полный список занятий преподавателя
      responses:
        '200':
          description: Список занятий успешно получен

  /teacher/lessons/{id}:
    get:
      tags: [Занятия]
      summary: Получить подробную информацию о занятии
      description: Возвращает детальную информацию о конкретном занятии
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор занятия
          schema:
            type: string
      responses:
        '200':
          description: Информация о занятии успешно получена
        '404':
          description: Занятие не найдено

  /teacher/lessons/{id}/zoom-link:
    get:
      tags: [Занятия]
      summary: Получить ссылку на Zoom конференцию
      description: Возвращает активную ссылку для проведения онлайн занятия
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор занятия
          schema:
            type: string
      responses:
        '200':
          description: Ссылка на Zoom успешно получена

  /teacher/lessons/{id}/files:
    get:
      tags: [Занятия]
      summary: Получить список файлов занятия
      description: Возвращает все материалы, прикрепленные к занятию
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор занятия
          schema:
            type: string
      responses:
        '200':
          description: Список файлов успешно получен
    
    post:
      tags: [Занятия]
      summary: Загрузить новый файл к занятию
      description: Позволяет прикрепить материалы к занятию
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор занятия
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Файл для загрузки
              required:
                - file
      responses:
        '201':
          description: Файл успешно загружен

  # ===== КУРСЫ =====
  /teacher/courses:
    get:
      tags: [Курсы]
      summary: Получить список курсов преподавателя
      description: Возвращает все курсы, которые ведет преподаватель
      responses:
        '200':
          description: Список курсов успешно получен

  /teacher/courses/{id}:
    get:
      tags: [Курсы]
      summary: Получить подробную информацию о курсе
      description: Возвращает детальную информацию о конкретном курсе
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Информация о курсе успешно получена

  /teacher/courses/{id}/preview:
    get:
      tags: [Курсы]
      summary: Получить превью курса
      description: Возвращает краткую информацию о курсе для предварительного просмотра
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Превью курса успешно получено

  /teacher/courses/{id}/students:
    get:
      tags: [Курсы]
      summary: Получить список студентов курса
      description: Возвращает всех студентов, записанных на курс
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Список студентов успешно получен

  /teacher/courses/{id}/lessons:
    get:
      tags: [Курсы]
      summary: Получить занятия курса
      description: Возвращает все занятия, входящие в курс
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Список занятий курса успешно получен

  /teacher/courses/{id}/media:
    get:
      tags: [Курсы]
      summary: Получить медиафайлы курса
      description: Возвращает все медиаматериалы курса (видео, аудио, изображения)
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Медиафайлы успешно получены

  # ===== СТУДЕНТЫ И ГРУППЫ =====
  /teacher/groups:
    get:
      tags: [Студенты и группы]
      summary: Получить список групп
      description: Возвращает все группы преподавателя
      responses:
        '200':
          description: Список групп успешно получен

  /teacher/groups/{id}/students:
    get:
      tags: [Студенты и группы]
      summary: Получить студентов группы
      description: Возвращает всех студентов в конкретной группе
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор группы
          schema:
            type: string
      responses:
        '200':
          description: Список студентов группы успешно получен

  /teacher/students:
    get:
      tags: [Студенты и группы]
      summary: Поиск студентов
      description: Возвращает список студентов с возможностью поиска по имени
      parameters:
        - name: search
          in: query
          required: false
          description: Строка для поиска студентов по имени или фамилии
          schema:
            type: string
            example: "Иван Петров"
      responses:
        '200':
          description: Результаты поиска успешно получены

  /teacher/students/{id}:
    get:
      tags: [Студенты и группы]
      summary: Получить профиль студента
      description: Возвращает подробную информацию о конкретном студенте
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор студента
          schema:
            type: string
      responses:
        '200':
          description: Профиль студента успешно получен

  # ===== ДОМАШНИЕ ЗАДАНИЯ =====
  /teacher/homework:
    get:
      tags: [Домашние задания]
      summary: Получить список домашних заданий
      description: Возвращает все домашние задания преподавателя
      responses:
        '200':
          description: Список домашних заданий успешно получен
    
    post:
      tags: [Домашние задания]
      summary: Создать новое домашнее задание
      description: Позволяет создать домашнее задание для студентов
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Название задания
                description:
                  type: string
                  description: Описание задания
                dueDate:
                  type: string
                  format: date-time
                  description: Срок выполнения
              required:
                - title
                - description
      responses:
        '201':
          description: Домашнее задание успешно создано

  /teacher/homework/{id}:
    get:
      tags: [Домашние задания]
      summary: Получить детали домашнего задания
      description: Возвращает подробную информацию о конкретном домашнем задании
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор домашнего задания
          schema:
            type: string
      responses:
        '200':
          description: Детали домашнего задания успешно получены

  # ===== ВИДЕОУРОКИ =====
  /teacher/video-lessons:
    get:
      tags: [Видеоуроки]
      summary: Получить список видеоуроков
      description: Возвращает все видеоуроки преподавателя
      responses:
        '200':
          description: Список видеоуроков успешно получен

  # ===== СООБЩЕНИЯ =====
  /teacher/messages:
    get:
      tags: [Сообщения]
      summary: Получить входящие сообщения
      description: Возвращает все сообщения преподавателя
      responses:
        '200':
          description: Сообщения успешно получены
    
    post:
      tags: [Сообщения]
      summary: Отправить сообщение
      description: Позволяет отправить сообщение студенту или группе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipientId:
                  type: string
                  description: ID получателя
                subject:
                  type: string
                  description: Тема сообщения
                content:
                  type: string
                  description: Текст сообщения
              required:
                - recipientId
                - content
      responses:
        '201':
          description: Сообщение успешно отправлено

  /teacher/messages/{id}:
    get:
      tags: [Сообщения]
      summary: Просмотреть конкретное сообщение
      description: Возвращает содержимое выбранного сообщения
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор сообщения
          schema:
            type: string
      responses:
        '200':
          description: Сообщение успешно получено

  # ===== ПРОФИЛЬ =====
  /teacher/profile:
    get:
      tags: [Профиль]
      summary: Получить профиль преподавателя
      description: Возвращает информацию о профиле текущего преподавателя
      responses:
        '200':
          description: Профиль успешно получен

  # ===== ПУБЛИЧНЫЕ ДАННЫЕ =====
  /teachers/{id}/public:
    get:
      tags: [Публичные данные]
      summary: Получить публичный профиль преподавателя
      description: Возвращает открытую информацию о преподавателе для просмотра студентами
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор преподавателя
          schema:
            type: string
      responses:
        '200':
          description: Публичный профиль успешно получен

  /teachers/{id}/courses:
    get:
      tags: [Публичные данные]
      summary: Получить курсы преподавателя (публично)
      description: Возвращает список доступных курсов преподавателя для записи
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор преподавателя
          schema:
            type: string
      responses:
        '200':
          description: Список курсов успешно получен

  /courses/{id}/public:
    get:
      tags: [Публичные данные]
      summary: Получить публичную информацию о курсе
      description: Возвращает открытую информацию о курсе для потенциальных студентов
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Публичная информация о курсе успешно получена

  /courses/{id}/preview:
    get:
      tags: [Публичные данные]
      summary: Получить превью курса (публично)
      description: Возвращает краткий обзор курса для ознакомления
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Превью курса успешно получено

  /courses/{id}/files:
    get:
      tags: [Публичные данные]
      summary: Получить доступные файлы курса
      description: Возвращает список файлов курса, доступных для скачивания
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Список файлов успешно получен

  /courses/{id}/start-date:
    get:
      tags: [Публичные данные]
      summary: Получить дату начала курса
      description: Возвращает информацию о дате начала курса
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор курса
          schema:
            type: string
      responses:
        '200':
          description: Дата начала курса успешно получена
